name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  playwright-tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
      
    - name: Build application
      run: npm run build
      env:
        CI: true
        
    - name: Start preview server
      run: |
        npx vite preview --port 3000 &
        npx wait-on http://localhost:3000
      
    - name: Run Playwright tests
      run: npx playwright test --browser=${{ matrix.browser }}
      env:
        CI: true
        BASE_URL: http://localhost:3000
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
        retention-days: 7
        
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-screenshots-${{ matrix.browser }}
        path: test-results/**/*.png
        retention-days: 7

  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
      
    - name: Build application
      run: npm run build
      
    - name: Start preview server
      run: |
        npx vite preview --port 3000 &
        npx wait-on http://localhost:3000
        
    - name: Run visual tests
      run: npx playwright test --grep @visual
      env:
        CI: true
        UPDATE_SNAPSHOTS: ${{ github.event_name == 'workflow_dispatch' }}
        
    - name: Upload visual diff report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: visual-regression-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  accessibility-tests:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Run axe accessibility tests
      run: |
        npx vite preview --port 3000 &
        npx wait-on http://localhost:3000
        npx axe http://localhost:3000 --save accessibility-report.json
        
    - name: Upload accessibility report
      uses: actions/upload-artifact@v4
      with:
        name: accessibility-report
        path: accessibility-report.json
        retention-days: 30