name: Maintenance

on:
  schedule:
    - cron: '0 3 * * 1' # Weekly on Monday at 3 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Update npm dependencies
      run: |
        # Update all dependencies to latest minor/patch versions
        npx npm-check-updates -u --target minor
        npm install
        npm audit fix || true
        
    - name: Run tests
      run: npm test -- --watchAll=false
      continue-on-error: true
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Weekly dependency updates'
        body: |
          ## Weekly Dependency Updates
          
          This PR contains automatic dependency updates for minor and patch versions.
          
          ### Changes
          - Updated npm dependencies to latest minor/patch versions
          - Ran npm audit fix for security updates
          
          ### Checklist
          - [ ] All tests pass
          - [ ] No breaking changes identified
          - [ ] Security vulnerabilities addressed
          
          Please review and merge if all checks pass.
        branch: deps/weekly-update
        delete-branch: true
        labels: |
          dependencies
          automated

  cleanup-artifacts:
    name: Cleanup Old Artifacts
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete old artifacts
      uses: actions/github-script@v7
      with:
        script: |
          const daysToKeep = 30;
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);
          
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });
          
          const oldArtifacts = artifacts.data.artifacts.filter(artifact => {
            return new Date(artifact.created_at) < cutoffDate;
          });
          
          console.log(`Found ${oldArtifacts.length} artifacts older than ${daysToKeep} days`);
          
          for (const artifact of oldArtifacts) {
            await github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id
            });
            console.log(`Deleted artifact: ${artifact.name}`);
          }

  cache-cleanup:
    name: Cache Cleanup
    runs-on: ubuntu-latest
    
    steps:
    - name: Cleanup caches
      uses: actions/github-script@v7
      with:
        script: |
          const caches = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });
          
          // Keep only the 10 most recent caches
          const cachesToDelete = caches.data.actions_caches.slice(10);
          
          for (const cache of cachesToDelete) {
            await github.rest.actions.deleteActionsCacheById({
              owner: context.repo.owner,
              repo: context.repo.repo,
              cache_id: cache.id
            });
            console.log(`Deleted cache: ${cache.key}`);
          }

  stale-issues:
    name: Mark Stale Issues
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity. 
          It will be closed in 7 days if no further activity occurs. 
          Thank you for your contributions.
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity. 
          It will be closed in 7 days if no further activity occurs. 
          Please update or merge the PR if it's still relevant.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned,security,bug'
        exempt-pr-labels: 'pinned,security'